export default function() {
    return [
        {
            "id": "1",
            "name": "name1",
            "email": "name1@email.com",
            "sort": 0,
            "passwd": "****"
        }, {
            "id": "2",
            "name": "name2",
            "email": "name2@email.com",
            "sort": 1,
            "passwd": "****",
            "selected": true
        }, {
            "id": "3",
            "name": "name3",
            "email": "name3@email.com",
            "sort": 2,
            "passwd": "****"
        }, {
            "id": "4",
            "name": "name4 this meant to be a long name, because a table should handle long texts in cells like this with ease",
            "email": "name4@email.com",
            "sort": 3,"passwd": "****"
        }, {
            "id": "5",
            "name": "name5 ékezetes betűk is jöhetnek hátha történik velük valami",
            "email": "name5@email.com",
            "sort": "a",
            "passwd": "****"
        }, {
            "id": "6",
            "name": "name6",
            "email": "name6@email.com",
            "sort": "á",
            "passwd": "****"
        }, {
            "id": "7",
            "name": "name7",
            "email": "name7@email.com",
            "sort": "b",
            "passwd": "****"
        }, {
            "id": "8",
            "name": "name8",
            "email": "name8@email.com",
            "sort": "bb",
            "passwd": "****"
        }, {
            "id": "9",
            "name": "name9",
            "email": "name9@email.com",
            "sort": "bbb",
            "passwd": "****"
        }, {
            "id": "10",
            "name": "name10",
            "email": "name10@email.com",
            "sort": "bb",
            "passwd": "****"
        }, {
            "id": "11",
            "name": "name11",
            "email": "name11@email.com",
            "sort": "olló",
            "passwd": "****"
        }, {
            "id": "12",
            "name": "name12",
            "email": "name12@email.com",
            "sort": "ólom",
            "passwd": "****"
        }, {
            "id": "13",
            "name": "name13",
            "email": "name13@email.com",
            "sort": "öröm",
            "passwd": "****"
        }, {
            "id": "14",
            "name": "name14",
            "email": "name14@email.com",
            "sort": "őr",
            "passwd": "****"
        }, {
            "id": "15",
            "name": "name15",
            "email": "name15@email.com",
            "sort": "pár",
            "passwd": "****"
        }, {
            "id": "16",
            "name": "name16",
            "email": "name16@email.com",
            "sort": 0.1,
            "passwd": "****"
        }, {
            "id": "17",
            "name": "name17",
            "email": "name17@email.com",
            "sort": 0.011,
            "passwd": "****"
        }, {
            "id": "18",
            "name": "name18",
            "email": "name18@email.com",
            "sort": 0.01,
            "passwd": "****"
        }, {
            "id": "19",
            "name": "name19",
            "email": "name19@email.com",
            "sort": 0.2,
            "passwd": "****"
        }
    ];
}
